version: '3.4'

services:
  #propostadb:
  #  container_name: banco_mongodb_corban
  #  restart: always
  #  environment:
  #    MONGO_INITDB_ROOT_USERNAME: macoratti
  #    MONGO_INITDB_ROOT_PASSWORD: numsey
  #  ports:
  #    - "27018:27017"
    #volumes:
    #  - mongo_propostadb_data:/data/db
  cartaoservicodb:
    container_name: cartaoservicodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: cartaouser
      MONGO_INITDB_ROOT_PASSWORD: cartaopws
    ports:
      - "27020:27017"
    volumes:
      - mongo_propostadb_data:/data/db
  rabbitmq:
    container_name: rabbitmq_management-alpine
    restart: always
    environment:
      - RABBITMQ_DEFAULT_USER = guest
      - RABBITMQ_DEFAULT_PASS = guest
    ports:
      - 5672:5672
      - 8080:15672
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
